"""add is_sellable to menus

Revision ID: 950bac1a71a7
Revises: 8753ce548ee0
Create Date: 2026-07-17 14:54:23.272363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950bac1a71a7'
down_revision: Union[str, Sequence[str], None] = '8753ce548ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy import text

def upgrade() -> None:
    op.add_column('menus', sa.Column('is_sellable', sa.Boolean(), nullable=False, server_default='true'))
    # backfill: item base-unit lama (misal "Lele (per ekor)") jangan tampil di kasir
    op.execute(text("""
        UPDATE menus SET is_sellable = false
        WHERE name ILIKE '%base unit%' OR name ILIKE '%per ekor%'
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
